### ISSUE TITLE
Problem with tsd reinstall when pulling older angular-ui modules

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [DefinitelyTyped/tsd#146]
Hi,

I seem to be having a problem with pulling the older ```angular-ui/angular-ui-router.t.ds```. When I look at the current HEAD branch, this seems to be moved into ```angular-ui-router/angular-ui-router.t.ds```. If I rename this, then my typescript project fails during compile (I think ```ng.ui``` modules changes to ```angular.ui```), which isn't exactly ideal.

The tsd.json posted below works when using an older version of tsd (0.5.7 for me) on tsd reinstall.

Below is the error, tsd.json and version information:

I am running ```tsd reinstall``` and I seem to be getting this error:

    Cannot read property 'commit' of null
    TypeError: Cannot read property 'commit' of null
        at ContentLoader.loadContent (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\build\tsd\logic\ContentLoader.js:44:63)
        at C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\build\tsd\logic\Installer.js:75:39
        at tryCatch1 (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\util.js:63:19)
        at Promise$_callHandler [as _callHandler] (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:695:13)
        at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:711:18)
        at Promise$_settlePromiseAt [as _settlePromiseAt] (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:868:14)
        at Promise$_settlePromises [as _settlePromises] (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:1006:14)
        at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\async.js:74:12)
        at Async$consumeFunctionBuffer (C:\Users\Shiraaz.Moollatjie\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\async.js:37:14)
        at process._tickCallback (node.js:355:11)

My tsd.json looks like this:

    {
      "version": "v4",
      "repo": "borisyankov/DefinitelyTyped",
      "ref": "master",
      "path": "typings",
      "bundle": "typings/tsd.d.ts",
      "installed": {
        "jasmine/jasmine.d.ts": {
          "commit": "0d999bb4663ec3212427c0b0ff28fc08c065e98d"
        },
        "angularjs/angular-mocks.d.ts": {
          "commit": "bba33bcb0b363ae41db8517a09d1a4d07828616b"
        },
        "jquery/jquery.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angularjs/angular.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "moment/moment.d.ts": {
          "commit": "5fe6713e8b2a05652a11bd26932ca0345fbb65ed"
        },
        "angular-hotkeys/angular-hotkeys.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angular-ui-bootstrap/angular-ui-bootstrap.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angular-ui/angular-ui-router.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "typeahead/typeahead.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angularjs/angular-resource.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "restangular/restangular.d.ts": {
          "commit": "35fffaa44bff5392741b3022d805fe3563023a3d"
        }
      }
    }

I am currently running on ```tsd 0.6.0-beta.5```, although this is was initially discovered on beta-4.

**Comment by Diullei** [comment]
@ShiraazMoollatjie I'll close this issue, this was fixed with the latest tsd version (0.6.0). If you still with problem we can reopen this issue.

Commit reference: https://github.com/DefinitelyTyped/tsd/pull/133

**Comment by neutmute** [comment]
Add a thumbs up reaction if your unmodified code suddenly started failing with this
