### ISSUE TITLE
Getting 403 on Travis CI

### ISSUE THREAD

**Issue by dbeckwith** [DefinitelyTyped/tsd#163]
I'm not sure whose issue this may be, Travis or tsd, but when my Travis build tries to run `tsd update -so`, I get this:

```console
Running "run:update_tsd" (run) task
-> running update
-> an error occured!
unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
Error: unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
    at Request.<anonymous> (/home/travis/.nvm/v0.10.38/lib/node_modules/tsd/build/http/CacheStreamLoader.js:158:28)
    at Request.emit (events.js:95:17)
    at Request.onRequestResponse (/home/travis/.nvm/v0.10.38/lib/node_modules/tsd/node_modules/request/request.js:1142:10)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at CleartextStream.socketOnData (http.js:1584:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
---
unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
/home/travis/.nvm/v0.10.38/lib/node_modules/tsd/node_modules/bluebird/js/main/async.js:93
                throw res.e;
                         ^
Error: unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
    at Request.<anonymous> (/home/travis/.nvm/v0.10.38/lib/node_modules/tsd/build/http/CacheStreamLoader.js:158:28)
    at Request.emit (events.js:95:17)
    at Request.onRequestResponse (/home/travis/.nvm/v0.10.38/lib/node_modules/tsd/node_modules/request/request.js:1142:10)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at CleartextStream.socketOnData (http.js:1584:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
Warning: non-zero exit code 8 Use --force to continue.
Aborted due to warnings.
```
But it works fine on my local machine.

**Comment by Diullei** [comment]
Hi, really seems to be a problem with github api access. Same issue here: http://stackoverflow.com/questions/30447362/travis-ci-status-code-403-on-github-api
I'll investigate. For now, change your .gitignore file to tracking the `typings` directory. This will avoid your build error.

**Comment by dbeckwith** [comment]
Okay thanks, I was considering that workaround.

**Comment by alexlrobertson** [comment]
I'm encountering this error on my local machine:

```
unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
Error: unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
    at Request.<anonymous> (/Users/arobertson/.nvm/versions/node/v0.12.4/lib/node_modules/tsd/build/http/CacheStreamLoader.js:158:28)
    at Request.emit (events.js:107:17)
    at Request.onRequestResponse (/Users/arobertson/.nvm/versions/node/v0.12.4/lib/node_modules/tsd/node_modules/request/request.js:1142:10)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
```

**Comment by Diullei** [comment]
@alexlrobertson, It seems that this error is related to github API access limit https://developer.github.com/v3/#rate-limiting

We have some instruction at the README explaning about how to use "Github OAuth token"

Could you test? https://github.com/DefinitelyTyped/tsd#tsdrc

**Comment by dbeckwith** [comment]
@Diullei, might that fix my issue as well?

**Comment by Diullei** [comment]
@dbeckwith I think so but I did not have time to test it with Travis. Could you test?

**Comment by dbeckwith** [comment]
@Diullei yes I will sometime today, I'll let you know if it works.

**Comment by Diullei** [comment]
@dbeckwith Thank you :+1:

**Comment by dbeckwith** [comment]
@Diullei Worked for me! :smile:

**Comment by Diullei** [comment]
@dbeckwith Good! :+1:  I'll wait @alexlrobertson feedback before to close this issue!

**Comment by alexlrobertson** [comment]
Seems to have fixed it.

**Comment by Diullei** [comment]
@alexlrobertson Good! :+1:
