### ISSUE TITLE
Bluebird parse error

### ISSUE THREAD

**Issue by sourcebits-robertbiggs** [DefinitelyTyped/tsd#176]
When I try to use the latest version of tsd, v0.6.3, to do an init, query or an install, I get the following error:
```
Unexpected token /
SyntaxError: Unexpected token /
    at Object.parse (native)
    at JSONStabilizer.parseString (/usr/local/lib/node_modules/tsd/build/xm/lib/JSONStabilizer.js:30:27)
    at Config.parseJSONString (/usr/local/lib/node_modules/tsd/build/tsd/context/Config.js:125:37)
    at /usr/local/lib/node_modules/tsd/build/tsd/logic/ConfigIO.js:44:43
    at tryCatch1 (/usr/local/lib/node_modules/tsd/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/usr/local/lib/node_modules/tsd/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/tsd/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/usr/local/lib/node_modules/tsd/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/usr/local/lib/node_modules/tsd/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/tsd/node_modules/bluebird/js/main/async.js:74:12)
```

I'm on Mac OS X El Capitan.

**Comment by blakeembrey** [comment]
@sourcebits-robertbiggs Is your `tsd.json` file valid JSON?

**Comment by chocolatechipui** [comment]
I do not have a tsd.json file in the project. I've simply installed tsd using npm: npm i -g tsd. Then when I run tsd init on a new project as per the instructions on the Github page, I get the above error.
If you're referring to tsd itself, digging through /usr/local/lib/node_modules/tsd I do not find a tsd.json file.

**Comment by chocolatechipui** [comment]
Actually, I've deleted tsd and reinstalled it a couple of times. Now tsd init and install are working fine. I'm assuming some minor part of something wasn't getting pulled down by NPM. You can close this issue.

**Comment by blakeembrey** [comment]
Ok. If you're still having issues, please feel free to open another issue :smile:
