### ISSUE TITLE
Handle the Github API 403 error with a friendly message.

### ISSUE THREAD

**Issue by Diullei** [DefinitelyTyped/tsd#178]
```
unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
Error: unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
    at Request.<anonymous> (C:\Users\DiulleiGomes\AppData\Roaming\npm\node_modules\tsd\build\http\CacheStreamLoader.js:
58:28)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestResponse (C:\Users\DiulleiGomes\AppData\Roaming\npm\node_modules\tsd\node_modules\request\reque
t.js:985:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:507:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
---
```
Related: https://github.com/DefinitelyTyped/tsd/issues/177

**Comment by Diullei** [comment]
done! 

https://github.com/DefinitelyTyped/tsd/blob/master/src/tsd/util/error-handler.ts#L33 

https://github.com/DefinitelyTyped/tsd/blob/0549c8aad6215605f45e3f388b82392b6a4cd0c7/src/http/CacheStreamLoader.ts#L236
