### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by IEvangelist** [DefinitelyTyped/tsd#254]
I'm attempting to install angular2 into my new Visual Studio 2015 web application, however; I'm having connection issues.  I am not behind a proxy, and I have ensured that I have no proxy settings configured.

Here is the output from the `tsd install angular2` command.

```
λ tsd install angular2
[ERR!] cwd  : C:\Users\cpined1\Documents\Visual Studio 2015\Projects\MvcWithAngular2\MvcWithAngular2
[ERR!] os   : Windows_NT 6.1.7601
[ERR!] argv : "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\cpined1\\AppData\\Roaming\\npm\\node_modules\\tsd\\build\\cli.js" "install" "angular2"
[ERR!] node : v4.2.3
[ERR!] tsd  : 0.6.5
[ERR!] Error: connect ECONNREFUSED 192.30.252.125:443
[ERR!] CODE : ECONNREFUSED
[ERR!] Error: connect ECONNREFUSED 192.30.252.125:443
[ERR!]
If you are behind a proxy, please make sure that the 'proxy' config
 is set properly.  See: https://github.com/DefinitelyTyped/tsd#tsdrc
[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    C:\Users\cpined1\Documents\Visual Studio 2015\Projects\MvcWithAngular2\MvcWithAngular2\tsd-debug.log
```

Please help me resolve this... also, here is the attached log file.

```
[ERR!] cwd  : C:\Users\cpined1\Documents\Visual Studio 2015\Projects\MvcWithAngular2\MvcWithAngular2
[ERR!] os   : Windows_NT 6.1.7601
[ERR!] argv : "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\cpined1\\AppData\\Roaming\\npm\\node_modules\\tsd\\build\\cli.js" "install" "angular2"
[ERR!] node : v4.2.3
[ERR!] tsd  : 0.6.5
[ERR!] Error: connect ECONNREFUSED 192.30.252.125:443
[ERR!] CODE : ECONNREFUSED
[ERR!] Error: connect ECONNREFUSED 192.30.252.125:443
[ERR!] 
If you are behind a proxy, please make sure that the 'proxy' config
 is set properly.  See: https://github.com/DefinitelyTyped/tsd#tsdrc
[ERR!] 
Error: connect ECONNREFUSED 192.30.252.125:443
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

[ERR!] tsd.json: {"version":"v4","repo":"borisyankov/DefinitelyTyped","ref":"master","path":"typings","bundle":"typings/tsd.d.ts","installed":{}}

[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    C:\Users\cpined1\Documents\Visual Studio 2015\Projects\MvcWithAngular2\MvcWithAngular2\tsd-debug.log
```

**Comment by IEvangelist** [comment]
Okay, I worked through this issue myself.  Now that I figured out this was related to a VPN, I can now successfully install, but where do these files actually install to?
