### ISSUE TITLE
React.js with Nodejs - TypeError:Path must be a string. Received true

### ISSUE THREAD

**Issue by ayyappan8582** [DefinitelyTyped/tsd#271]
When i run the below command in nodejs, i got "TypeError:Path must be a string. Received true"
==========================================================================
D:\projects\infiswift\infi.admin\public>babel --presets react D:\projects\infisw
ift\infi.admin\public\assets\js\hello-world.js --watch --out-dir
TypeError: Path must be a string. Received true
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at write (C:\Users\Aximsoft\AppData\Roaming\npm\node_modules\babel-cli\lib\b
abel\dir.js:17:21)
    at handle (C:\Users\Aximsoft\AppData\Roaming\npm\node_modules\babel-cli\lib\
babel\dir.js:65:7)
    at arrayEach (C:\Users\Aximsoft\AppData\Roaming\npm\node_modules\babel-cli\n
ode_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Users\Aximsoft\AppData\Roaming\npm\node_modules\
babel-cli\node_modules\lodash\index.js:3345:13)
    at module.exports (C:\Users\Aximsoft\AppData\Roaming\npm\node_modules\babel-
cli\lib\babel\dir.js:69:5)
    at Object.<anonymous> (C:\Users\Aximsoft\AppData\Roaming\npm\node_modules\ba
bel-cli\lib\babel\index.js:124:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by blakeembrey** [comment]
@ayyappan8582 I don't see TSD used? It looks like you're using Babel?

**Comment by basarat** [comment]
Closing as probably wrong repo.

Feel free to continue discussion if we were wrong :rose:
