### ISSUE TITLE
Error, code undefined, unexpected token, Windows 10

### ISSUE THREAD

**Issue by edgar0011** [DefinitelyTyped/tsd#278]
[ERR!] cwd  : C:\TBC_IBS\tbc-ibs\tbcibs\server\angular
[ERR!] os   : Windows_NT 10.0.10586
[ERR!] argv : "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\onderka\\AppData\\Roaming\\npm\\node_modules\\tsd\\build\\cli.js" "install"
[ERR!] node : v4.3.1
[ERR!] tsd  : 0.6.5
[ERR!] Error: Unexpected token 
[ERR!] CODE : undefined
[ERR!] Unexpected token 
[ERR!] If you need help, you may report this error at:
    https://github.com/DefinitelyTyped/tsd/issues

[ERR!] 
SyntaxError: Unexpected token 
    at Object.parse (native)
    at C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\build\http\HTTPCache.js:131:39
    at tryCatch1 (C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\util.js:63:19)
    at Promise$_callHandler [as _callHandler] (C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\async.js:74:12)
    at Async$consumeFunctionBuffer (C:\Users\onderka\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\async.js:37:14)
    at nextTickCallbackWith0Args (node.js:415:9)

[ERR!] tsd.json: {"version":"v4","repo":"borisyankov/DefinitelyTyped","ref":"master","path":"typings","bundle":"typings/tsd.d.ts","installed":{"angularjs/angular.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"requirejs/require.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"jquery/jquery.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"angular-file-upload/angular-file-upload.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"angular-ui-router/angular-ui-router.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"jasmine/jasmine.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"angular-translate/angular-translate.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"bootstrap/bootstrap.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"angularjs/angular-resource.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"es6-promise/es6-promise.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx-lite.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.all.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.aggregates.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.time.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.async.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.time-lite.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.async-lite.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.binding.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.binding-lite.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.coincidence.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.coincidence-lite.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.experimental.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.testing.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.virtualtime.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.joinpatterns.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.backpressure.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"rx/rx.backpressure-lite.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"moment/moment.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"moment/moment-node.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"q/Q.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"angularjs/angular-animate.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"},"ng-file-upload/ng-file-upload.d.ts":{"commit":"ab2462147a313f69e7118625cfcce21c005fa4af"}}}

[ERR!] .tsdrc : {
    "strictSSL": false
}

[ERR!] Please include the following file with any support request:
    C:\TBC_IBS\tbc-ibs\tbcibs\server\angular\tsd-debug.log

**Comment by nflorian** [comment]
Hi,

I have the same issue.
Did you find a fix for this ?

Thx
