### ISSUE TITLE
cannot run tsd install 

### ISSUE THREAD

**Issue by zaherz** [DefinitelyTyped/tsd#291]
Hello,

I'm unable to run **tsd install _any_ --save** 

see below exception

Unexpected end of input
[ERR!] cwd  : C:\Users\zkhater\Documents\ccm_wa\check_tsd
[ERR!] os   : Windows_NT 10.0.10586
[ERR!] argv : "C:\Program Files\nodejs\node.exe" "C:\Users\zkhater\AppData\Roaming\npm\node_modules\tsd\build\cli.js" "install" "jquery" "--save"
[ERR!] node : v4.6.0
[ERR!] tsd  : 0.6.5
[ERR!] Error: Unexpected end of input
[ERR!] CODE : undefined
[ERR!] Unexpected end of input
[ERR!] If you need help, you may report this error at:
    https://github.com/DefinitelyTyped/tsd/issues

[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    C:\Users\zkhater\Documents\ccm_wa\check_tsd\tsd-debug.log

**tsd-debug.log content:**

[ERR!] cwd  : C:\Users\zkhater\Documents\ccm_wa\check_tsd
[ERR!] os   : Windows_NT 10.0.10586
[ERR!] argv : "C:\Program Files\nodejs\node.exe" "C:\Users\zkhater\AppData\Roaming\npm\node_modules\tsd\build\cli.js" "install" "jquery" "--save"
[ERR!] node : v4.6.0
[ERR!] tsd  : 0.6.5
[ERR!] Error: Unexpected end of input
[ERR!] CODE : undefined
[ERR!] Unexpected end of input
[ERR!] If you need help, you may report this error at:
    https://github.com/DefinitelyTyped/tsd/issues

[ERR!] 
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at C:\Users\zkhater\AppData\Roaming\npm\node_modules\tsd\build\http\HTTPCache.js:131:39
    at tryCatch1 (C:\Users\zkhater\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\util.js:63:19)
    at Promise$_callHandler [as _callHandler](C:UserszkhaterAppDataRoamingnpmnode_modulestsdnode_modulesbluebirdjsmainpromise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler](C:UserszkhaterAppDataRoamingnpmnode_modulestsdnode_modulesbluebirdjsmainpromise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt](C:UserszkhaterAppDataRoamingnpmnode_modulestsdnode_modulesbluebirdjsmainpromise.js:868:14)
    at Promise$_settlePromises [as _settlePromises](C:UserszkhaterAppDataRoamingnpmnode_modulestsdnode_modulesbluebirdjsmainpromise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer](C:UserszkhaterAppDataRoamingnpmnode_modulestsdnode_modulesbluebirdjsmainasync.js:74:12)
    at Async$consumeFunctionBuffer (C:\Users\zkhater\AppData\Roaming\npm\node_modules\tsd\node_modules\bluebird\js\main\async.js:37:14)
    at nextTickCallbackWith0Args (node.js:420:9)

[ERR!] tsd.json: {"version":"v4","repo":"borisyankov/DefinitelyTyped","ref":"master","path":"typings","bundle":"typings/tsd.d.ts","installed":{}}

[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    C:\Users\zkhater\Documents\ccm_wa\check_tsd\tsd-debug.log

**Comment by zaherz** [comment]
After a deep investigation i was able to fix the issue.

I did below steps:
1- removed all the content of: %appdata%\npm
2- removed all the content of: %appdata%\npm-cache
3- removed all the content of: %appdata%\tsd-cache
4- open new console and run first npm install tsd -g
5- then run npm install typescript -g

tsd install --save ran as expected!
