### ISSUE TITLE
Unexpected token   in JSON at position 0

### ISSUE THREAD

**Issue by nflorian** [DefinitelyTyped/tsd#294]
Hi,

I cannot get rid of this error, already tried a fresh reinstall

Any help is welcome,
Thanks

[ERR!] os   : Windows_NT 6.1.7601
[ERR!] argv : "C:\\Users\\Public\\Documents\\programs\\git\\nodejs\\node.exe" "C:\\Users\\Public\\Documents\\programs\\git\\nodejs\\node_modules\\tsd\\build\\cli.js" "install"
[ERR!] node : v6.2.1
[ERR!] tsd  : 0.6.5
[ERR!] Error: Unexpected token   in JSON at position 0
[ERR!] CODE : undefined
[ERR!] Unexpected token   in JSON at position 0
[ERR!] If you need help, you may report this error at:
    https://github.com/DefinitelyTyped/tsd/issues

[ERR!] 
SyntaxError: Unexpected token   in JSON at position 0
    at Object.parse (native)
    at C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\build\http\HTTPCache.js:131:39
    at tryCatch1 (C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\node_modules\bluebird\js\main\util.js:63:19)
    at Promise$_callHandler [as _callHandler] (C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\node_modules\bluebird\js\main\promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\node_modules\bluebird\js\main\promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\node_modules\bluebird\js\main\promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\node_modules\bluebird\js\main\promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\node_modules\bluebird\js\main\async.js:74:12)
    at Async$consumeFunctionBuffer (C:\Users\Public\Documents\programs\git\nodejs\node_modules\tsd\node_modules\bluebird\js\main\async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

[ERR!] **tsd.json:** {"version":"v4","repo":"borisyankov/DefinitelyTyped","ref":"master","path":"typings","bundle":"typings/tsd.d.ts","installed":{"angularjs/angular.d.ts":{"commit":"e623c6b3164bb8c6da508f84f7865eaaa97e1a0f"},"angularjs/angular-animate.d.ts":{"commit":"e623c6b3164bb8c6da508f84f7865eaaa97e1a0f"},"angularjs/angular-cookies.d.ts":{"commit":"98d3168c2c570352a3a7393788e2ec9fbb08ade6"},"jquery/jquery.d.ts":{"commit":"e623c6b3164bb8c6da508f84f7865eaaa97e1a0f"},"angularjs/angular-mocks.d.ts":{"commit":"98d3168c2c570352a3a7393788e2ec9fbb08ade6"},"angular-ui-router/angular-ui-router.d.ts":{"commit":"98d3168c2c570352a3a7393788e2ec9fbb08ade6"},"jasmine/jasmine.d.ts":{"commit":"98d3168c2c570352a3a7393788e2ec9fbb08ade6"},"lodash/lodash.d.ts":{"commit":"ebc69904eb78f94030d5d517b42db20867f679c0"},"systemjs/systemjs.d.ts":{"commit":"94d8775a947f626269b06ccadd6f5e61839389d0"},"moment/moment.d.ts":{"commit":"b2d754f53fe0b0418625c5ee6023a18c5c46cb4d"},"moment/moment-node.d.ts":{"commit":"b2d754f53fe0b0418625c5ee6023a18c5c46cb4d"}}}

[ERR!] .tsdrc : {
"token": "c2b025a4f657f451bf5cf751ba4ae8e2d8r53609"
}

**tsd.d.ts**
/// <reference path="angular-ui-router/angular-ui-router.d.ts" />
/// <reference path="angularjs/angular-animate.d.ts" />
/// <reference path="angularjs/angular-cookies.d.ts" />
/// <reference path="angularjs/angular-mocks.d.ts" />
/// <reference path="angularjs/angular.d.ts" />
/// <reference path="jasmine/jasmine.d.ts" />
/// <reference path="jquery/jquery.d.ts" />
/// <reference path="lodash/lodash.d.ts" />
/// <reference path="systemjs/systemjs.d.ts" />

**Comment by blakeembrey** [comment]
You probably have a BOM at the beginning of the file.
