### ISSUE TITLE
Syntax Error on typings init

### ISSUE THREAD

**Issue by mAMY-SCRATCH** [DefinitelyTyped/tsd#295]
I got a SyntaxError on my new machine after trying to run typings _init,_

`C:\Windows\system32>typings init
C:\Users\mchenard\AppData\Roaming\npm\node_modules\typings\node_modules\typings-
core\node_modules\strip-bom\index.js:2
module.exports = x => {
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\mchenard\AppData\Roaming\npm\node_modules\ty
pings\node_modules\typings-core\dist\utils\fs.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)`

**Comment by mAMY-SCRATCH** [comment]
Ran cmd.exe in admin and it worked... curious

**Comment by blakeembrey** [comment]
The tool you're using is `typings`, not TSD. Also the error means you're using a super old version of node.js that can't understand the syntax - probably 0.10 which is unsupported.
