### ISSUE TITLE
Support an API token for rate limit release

### ISSUE THREAD

**Issue by vvakame** [DefinitelyTyped/tsd#74]
Please support an API token for rate limit release.
https://github.com/DefinitelyTyped/tsd#github-rate-limit
This problem happened in the office that there is me.

with grunt-tsd

```
Running "tsd:client" (tsd) task
-> config: ./tsd.json
error!
Error: unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
    at Request.<anonymous> (/Users/vvakame/work/server/node_modules/grunt-tsd/node_modules/tsd/build/api.js:4442:34)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onResponse (/Users/vvakame/work/server/node_modules/grunt-tsd/node_modules/tsd/node_modules/request/request.js:827:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Socket.pipeOnReadable (_stream_readable.js:624:5)
    at Socket.EventEmitter.emit (events.js:92:17)    at emitReadable (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
Warning: Task "tsd:client" failed. Use --force to continue.
```

Check for a response from github.

``` bash
$ curl  -i https://api.github.com/users/whatever
HTTP/1.1 403 Forbidden
Server: GitHub.com  
Date: Tue, 11 Mar 2014 04:57:12 GMT
Content-Type: application/json; charset=utf-8
Status: 403 Forbidden
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1394517224
X-GitHub-Media-Type: github.beta
X-Content-Type-Options: nosniff
Content-Length: 258 
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: DEE5E3DF:7B0C:A8C572:531E97A7

{
  "message": "API rate limit exceeded for 222.229.227.223. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "http://developer.github.com/v3/#rate-limiting"
} 
```

and my tsd.json

``` bash
$ cat tsd.json
{
    "version": "v4",
    "repo": "borisyankov/DefinitelyTyped",
    "ref": "master",
    "path": "src/main/typescript/typings",
    "bundle": "src/main/typescript/typings/bundle.d.ts",
    "installed": {
        "jquery/jquery.d.ts": {
            "commit": "0854df3b0f7187ae445453aaad2563a97b70df08"
        },
        "angularjs/angular.d.ts": {
            "commit": "0854df3b0f7187ae445453aaad2563a97b70df08"
        },
        "angularjs/angular-mocks.d.ts": {
            "commit": "0854df3b0f7187ae445453aaad2563a97b70df08"
        },
        "angularjs/angular-route.d.ts": {
            "commit": "0854df3b0f7187ae445453aaad2563a97b70df08"
        },
        "mocha/mocha.d.ts": {
            "commit": "0854df3b0f7187ae445453aaad2563a97b70df08"
        },
        "chai/chai.d.ts": {
            "commit": "0854df3b0f7187ae445453aaad2563a97b70df08"
        }
    }
}
```

my Gruntfile.js

```
/// Gruntfile.json
                tsd: {
                        client: {
                                options: {
                                        // execute a command
                                        command: 'reinstall',

                                        //optional: always get from HEAD
                                        latest: false,

                                        // optional: specify config file
                                        config: './tsd.json'
                                }
                        }
                },
```

homebrew's solution
http://stackoverflow.com/questions/20130681/setting-github-api-token-for-homebrew

---

It may be another problem, but it is willing cache is not enabled?
not exists `0854df3b0f7187ae445453aaad2563a97b70df08`

``` bash
$ find ~/.tsd-cache
/Users/vvakame/.tsd-cache
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-api-v3.0.0-fmt1.0
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-api-v3.0.0-fmt1.0/51
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-api-v3.0.0-fmt1.0/83
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-api-v3.0.0-fmt1.0/83/83b1e137418a79e2e25c07eac78a6ffa1f3727f2.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-api-v3.0.0-fmt1.0/83/83b1e137418a79e2e25c07eac78a6ffa1f3727f2.raw
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-api-v3.0.0-fmt1.0/_info.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-api-v3.0.0-fmt1.0/b5
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/19
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/19/1971aa9c880b2211f1fdc822f83a5a4395f3f23a.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/19/1971aa9c880b2211f1fdc822f83a5a4395f3f23a.raw
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/_info.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/be
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/be/be6cc5afc78efdc17f57a5aa3b1caac2e9e435b4.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/be/be6cc5afc78efdc17f57a5aa3b1caac2e9e435b4.raw
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/cb
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/cb/cb06387a0110f30d73b5f464bb3c1b9c148f8763.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/cb/cb06387a0110f30d73b5f464bb3c1b9c148f8763.raw
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/d5
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/d5/d5a3a92bfabd1164b0f5b9c924a45f4085d102ab.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/d5/d5a3a92bfabd1164b0f5b9c924a45f4085d102ab.raw
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/d8
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/d8/d86bd51b08cd92414fc1cc7b28a9355d1f293c6d.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/d8/d86bd51b08cd92414fc1cc7b28a9355d1f293c6d.raw
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/e5
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/e5/e55ce68613cf6993929335d66a61d0b6e94d177d.json
/Users/vvakame/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/e5/e55ce68613cf6993929335d66a61d0b6e94d177d.raw
```

**Comment by minrk** [comment]
For build environments like Travis, it would be great if the token could be retrieved from an environment variable instead of needing to be in a file. If GitHub finds a token in plaintext committed to a repo, the token will be revoked.

**Comment by timoweiss** [comment]
:+1: For environment variable. Almost every third build crashes due to 403.

**Comment by Strate** [comment]
You can ever use standard `GITHUB_TOKEN` variable, which used by official client https://github.com/github/hub
